export enum ContactRelationship {
  "No relation" = 0,
  "Assistant" = 1,
  "Brother" = 2,
  "Child" = 3,
  "Domestic partner" = 4,
  "Father" = 5,
  "Friend" = 6,
  "Manager" = 7,
  "Mother" = 8,
  "Partner" = 9,
  "Parent" = 10,
  "Relative" = 11,
  "Sister" = 12,
  "Spouse" = 13,
}
